"""initial schema

Revision ID: bc92f1e9756d
Revises: 34a297efd01c
Create Date: 2026-05-17 01:38:39.988706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc92f1e9756d'
down_revision: Union[str, None] = '34a297efd01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
